services:
  spring-petclinic:
    image: spring-petclinic
    build:
      context: ~/spring-petclinic
    ports:
      - "8080:8080"
      - "12345:12345"
    networks:
      - prometheus

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - /etc/prometheus:/etc/prometheus
    networks:
      - prometheus
  
  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - prometheus
  
  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    volumes:
      - /etc/loki:/mnt/config
      - /var/log:/var/log/host_logs
    command: -config.file=/mnt/config/loki-config.yaml
    networks:
      - prometheus

  promtail:
    image: grafana/promtail
    volumes:
      - /var/log:/var/log
      - /etc/promtail:/mnt/config
    command: -config.file=/mnt/config/promtail-config.yaml
    networks:
      - prometheus

networks:
  prometheus:
    driver: bridge

volumes:
  grafana-storage: